/**
 * This class is generated by jOOQ
 */
package ru.doccloud.document.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.doccloud.document.jooq.db.Keys;
import ru.doccloud.document.jooq.db.Public;
import ru.doccloud.document.jooq.db.tables.records.GroupsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Groups extends TableImpl<GroupsRecord> {

	private static final long serialVersionUID = -1581612041;

	/**
	 * The reference instance of <code>public.groups</code>
	 */
	public static final Groups GROUPS = new Groups();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<GroupsRecord> getRecordType() {
		return GroupsRecord.class;
	}

	/**
	 * The column <code>public.groups.title</code>.
	 */
	public final TableField<GroupsRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.groups.id</code>.
	 */
	public final TableField<GroupsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>public.groups</code> table reference
	 */
	public Groups() {
		this("groups", null);
	}

	/**
	 * Create an aliased <code>public.groups</code> table reference
	 */
	public Groups(String alias) {
		this(alias, GROUPS);
	}

	private Groups(String alias, Table<GroupsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Groups(String alias, Table<GroupsRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<GroupsRecord> getPrimaryKey() {
		return Keys.ID_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<GroupsRecord>> getKeys() {
		return Arrays.<UniqueKey<GroupsRecord>>asList(Keys.ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Groups as(String alias) {
		return new Groups(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Groups rename(String name) {
		return new Groups(name, null);
	}
}
