/**
 * This class is generated by jOOQ
 */
package ru.doccloud.document.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.doccloud.document.jooq.db.Keys;
import ru.doccloud.document.jooq.db.Public;
import ru.doccloud.document.jooq.db.tables.records.RolesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles extends TableImpl<RolesRecord> {

	private static final long serialVersionUID = 2127717753;

	/**
	 * The reference instance of <code>public.roles</code>
	 */
	public static final Roles ROLES = new Roles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RolesRecord> getRecordType() {
		return RolesRecord.class;
	}

	/**
	 * The column <code>public.roles.role</code>.
	 */
	public final TableField<RolesRecord, String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>public.roles</code> table reference
	 */
	public Roles() {
		this("roles", null);
	}

	/**
	 * Create an aliased <code>public.roles</code> table reference
	 */
	public Roles(String alias) {
		this(alias, ROLES);
	}

	private Roles(String alias, Table<RolesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Roles(String alias, Table<RolesRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RolesRecord> getPrimaryKey() {
		return Keys.ROLES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RolesRecord>> getKeys() {
		return Arrays.<UniqueKey<RolesRecord>>asList(Keys.ROLES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Roles as(String alias) {
		return new Roles(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Roles rename(String name) {
		return new Roles(name, null);
	}
}
