/**
 * This class is generated by jOOQ
 */
package ru.doccloud.document.jooq.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.doccloud.document.jooq.db.Keys;
import ru.doccloud.document.jooq.db.Public;
import ru.doccloud.document.jooq.db.tables.records.TodosRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Todos extends TableImpl<TodosRecord> {

	private static final long serialVersionUID = -437301151;

	/**
	 * The reference instance of <code>public.todos</code>
	 */
	public static final Todos TODOS = new Todos();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TodosRecord> getRecordType() {
		return TodosRecord.class;
	}

	/**
	 * The column <code>public.todos.id</code>.
	 */
	public final TableField<TodosRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.todos.creation_time</code>.
	 */
	public final TableField<TodosRecord, Timestamp> CREATION_TIME = createField("creation_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.todos.description</code>.
	 */
	public final TableField<TodosRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.todos.modification_time</code>.
	 */
	public final TableField<TodosRecord, Timestamp> MODIFICATION_TIME = createField("modification_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.todos.title</code>.
	 */
	public final TableField<TodosRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>public.todos</code> table reference
	 */
	public Todos() {
		this("todos", null);
	}

	/**
	 * Create an aliased <code>public.todos</code> table reference
	 */
	public Todos(String alias) {
		this(alias, TODOS);
	}

	private Todos(String alias, Table<TodosRecord> aliased) {
		this(alias, aliased, null);
	}

	private Todos(String alias, Table<TodosRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TodosRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TODOS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TodosRecord> getPrimaryKey() {
		return Keys.TODOS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TodosRecord>> getKeys() {
		return Arrays.<UniqueKey<TodosRecord>>asList(Keys.TODOS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Todos as(String alias) {
		return new Todos(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Todos rename(String name) {
		return new Todos(name, null);
	}
}
