/**
 * This class is generated by jOOQ
 */
package ru.doccloud.document.jooq.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.doccloud.document.jooq.db.Sequences;
import ru.doccloud.document.jooq.db.tables.Documents;
import ru.doccloud.document.jooq.db.tables.Groups;
import ru.doccloud.document.jooq.db.tables.Links;
import ru.doccloud.document.jooq.db.tables.Roles;
import ru.doccloud.document.jooq.db.tables.System;
import ru.doccloud.document.jooq.db.tables.Todos;
import ru.doccloud.document.jooq.db.tables.UserRoles;
import ru.doccloud.document.jooq.db.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = 1128255280;

	/**
	 * The reference instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.DOCUMENTS_ID_SEQ,
			Sequences.SYSTEM_ID_SEQ);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Documents.DOCUMENTS,
			Groups.GROUPS,
			Links.LINKS,
			Roles.ROLES,
			System.SYSTEM,
			Todos.TODOS,
			UserRoles.USER_ROLES,
			Users.USERS);
	}
}
