/**
 * This class is generated by jOOQ
 */
package ru.doccloud.document.jooq.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;

import ru.doccloud.document.jooq.db.Public;


/**
 * Convenience access to all sequences in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.documents_id_seq</code>
	 */
	public static final Sequence<Long> DOCUMENTS_ID_SEQ = new SequenceImpl<Long>("documents_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.system_id_seq</code>
	 */
	public static final Sequence<Long> SYSTEM_ID_SEQ = new SequenceImpl<Long>("system_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.todos_id_seq</code>
	 */
	public static final Sequence<Long> TODOS_ID_SEQ = new SequenceImpl<Long>("todos_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
