/**
 * This class is generated by jOOQ
 */
package ru.doccloud.document.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.doccloud.document.jooq.db.tables.Groups;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupsRecord extends UpdatableRecordImpl<GroupsRecord> implements Record2<String, String> {

	private static final long serialVersionUID = -1134477598;

	/**
	 * Setter for <code>public.groups.title</code>.
	 */
	public void setTitle(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.groups.title</code>.
	 */
	public String getTitle() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.groups.id</code>.
	 */
	public void setId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.groups.id</code>.
	 */
	public String getId() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Groups.GROUPS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Groups.GROUPS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupsRecord value1(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupsRecord value2(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupsRecord values(String value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GroupsRecord
	 */
	public GroupsRecord() {
		super(Groups.GROUPS);
	}

	/**
	 * Create a detached, initialised GroupsRecord
	 */
	public GroupsRecord(String title, String id) {
		super(Groups.GROUPS);

		setValue(0, title);
		setValue(1, id);
	}
}
