/**
 * This class is generated by jOOQ
 */
package ru.doccloud.document.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.doccloud.document.jooq.db.tables.UserRoles;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRolesRecord extends UpdatableRecordImpl<UserRolesRecord> implements Record2<String, String> {

	private static final long serialVersionUID = -553021669;

	/**
	 * Setter for <code>public.user_roles.role</code>.
	 */
	public void setRole(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.user_roles.role</code>.
	 */
	public String getRole() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.user_roles.userid</code>.
	 */
	public void setUserid(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.user_roles.userid</code>.
	 */
	public String getUserid() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, String> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return UserRoles.USER_ROLES.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return UserRoles.USER_ROLES.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRolesRecord value1(String value) {
		setRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRolesRecord value2(String value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRolesRecord values(String value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRolesRecord
	 */
	public UserRolesRecord() {
		super(UserRoles.USER_ROLES);
	}

	/**
	 * Create a detached, initialised UserRolesRecord
	 */
	public UserRolesRecord(String role, String userid) {
		super(UserRoles.USER_ROLES);

		setValue(0, role);
		setValue(1, userid);
	}
}
