
server:
  port: 8888
  contextPath: /jooq

security:
  basic:
    enabled: true

spring:
  jmx:
    enabled: false
  datasource:
    jndi-name: jdbc/DOCCLOUDDB

logging:
  level:
    org.springframework.security: DEBUG
    ru.doccloud: DEBUG
#  user:
#    name: test
#    password: test
