
server:
  port: 8888
  contextPath: /jooq

security:
  basic:
    enabled: true

spring:
  jmx:
    enabled: false
  datasource:
    jndi-name: jdbc/DOCCLOUDDB
  ldap:
    embedded:
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
      port: 8389


logging:
  level:
    org.springframework.security: TRACE
    ru.doccloud.webapp: TRACE
